# Generated by Django 3.1.2 on 2020-10-26 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0005_auto_20201025_2322'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='author',
            new_name='user',
        ),
    ]
