# Generated by Django 3.1.2 on 2020-10-26 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0006_auto_20201026_1158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='comments',
        ),
    ]
