# Generated by Django 3.1.2 on 2020-10-26 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('awwards', '0007_remove_project_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='content',
        ),
    ]
